--- #YAML:1.0
name:                Dotiac
version:             0.4
abstract: |-
  Render Django Templates in Perl
license:             MIT
author:              
  - Marc Lucksch <perl@marc-s.de>
distribution_type:   module
requires:     
    Scalar::Util:                    0
    Data::Dumper:                    0
    File::Temp:                      0
    Carp:                            0
    File::Spec:                      0
    File::Basename:                  0
    Digest::MD5:                     0
recommends:
    POSIX:                           0
build_requires:
    Test::More:                      0
    Test::Pod:                       0
provides:
   Dotiac::DTL:
     file: lib/Dotiac/DTL.pm
     version: 0.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
